const JAVA_VERSION = '1.8';
const SPRING_BOOT_VERSION = '2.2.4.RELEASE';

const SPRING_DEP_MNGMNT_VERSION = '1.0.9.RELEASE';
const DEFAULT_APP_VERSION = '0.0.1-SNAPSHOT';
const PROBLEM_SPRING_WEB_VERSION = '0.25.2';
const SPRING_BOOT_TC_STARTER_VERSION = '1.36';


const constants = {
    JAVA_VERSION,
    SPRING_BOOT_VERSION,
    SPRING_DEP_MNGMNT_VERSION,
    DEFAULT_APP_VERSION,
    PROBLEM_SPRING_WEB_VERSION,
    SPRING_BOOT_TC_STARTER_VERSION
};

module.exports = constants;